apiVersion: v1
kind: PersistentVolume
metadata:
  name: be-pv
  labels:
    volume: be
spec:
  storageClassName: doris-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/be
    type: DirectoryOrCreate