apiVersion: v1
kind: PersistentVolume
metadata:
  name: fe-pv
  labels:
    volume: fe
spec:
  storageClassName: doris-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/fe
    type: DirectoryOrCreate