apiVersion: v1
kind: PersistentVolume
metadata:
  name: fe-pv-meta
  labels:
    volume: fe-meta
spec:
  storageClassName: doris-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/fe-meta
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fe-pv-log
  labels:
    volume: fe-log
spec:
  storageClassName: doris-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/fe-log
    type: DirectoryOrCreate